In [12]:
import pandas as pd
import re
import sentencepiece as spm
from pyvi import ViTokenizer

In [13]:
df = pd.read_json(r'D:\projec_ds\data\traffic_clean_9.json')

In [14]:
df.head(1)

,title,content
0,Bộ trưởng Giao thông Mỹ tuyên bố cải cách FAA ...,"Thông tin trên tài khoản mạng xã hội X, Bộ trư..."

# clean base

In [15]:

def clean_text(text):
    if pd.isnull(text):
        return ""
    text = text.lower()
    # Giữ lại . ? ! để dùng cho tách câu
    text = re.sub(r'[^a-zA-ZÀ-ỹ0-9%\s\.\,\"]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text
def sentence_segmentation(text):
    if not text:
        return []
    # Tách theo ., ?, ! hoặc xuống dòng
    sentences = re.split(r'[.\n]+', text)
    # Loại bỏ câu trống
    sentences = [s.strip() for s in sentences if s.strip()]
    return sentences
def normalize_sentence_case(sentence):
    sentence = sentence.strip()
    if not sentence:
        return ""
    sentence = sentence.lower()                     # toàn bộ về thường
    sentence = sentence[0].upper() + sentence[1:]   # viết hoa chữ đầu
    return sentence

In [16]:
df['content'] = df['content'].apply(clean_text)

df['content'] = df['content'].apply(sentence_segmentation)

df['content'] = df['content'].apply(
    lambda sentences: [normalize_sentence_case(s) for s in sentences]
)

In [17]:
df

,title,content
0,Bộ trưởng Giao thông Mỹ tuyên bố cải cách FAA ...,"[Thông tin trên tài khoản mạng xã hội x, bộ tr..."
1,Cao tốc Pháp Vân - Cầu Giẽ ùn ứ kéo dài chiều ...,[Theo ghi nhận của pv báo giao thông trong chi...
2,Tai nạn giao thông làm 33 người tử vong ngày m...,"[Chiều 31 1, đại diện cục csgt bộ công an cho ..."
3,Du xuân Đà Lạt bằng tàu cổ có gì hấp dẫn?,"[Chi nhánh vận tải đường sắt sài gòn cho biết,..."
4,Hơn 4.800 tài xế vi phạm giao thông ngày Mùng ...,"[Ảnh minh họa, Ngày 31 1, cục csgt bộ công an ..."
...,...,...
2905,Truy tìm tài xế ô tô tải bỏ chạy sau va chạm x...,"[Chiều 20 8, công an xã bình mỹ, tp, Hcm đang ..."
2906,"Xe container va chạm xe máy, cụ ông 76 tuổi tử...","[Khoảng 8h30 ngày 20 8, xe container biển số 5..."
2907,'Thót tim' xe ôm công nghệ phóng ngược chiều t...,[Mạng xã hội mới đây xuất hiện một đoạn video ...
2908,"Tạm ngưng lưu thông ôtô qua cầu Bình Triệu 1, ...","[Tpo bắt đầu từ 16 giờ 40 ngày 26 8, xe ô tô b..."
2909,Chi tiết các tuyến cấm đường vào ngày mai để p...,[Tpo công an tp hà nội thông báo phân luồng gi...

# tách token

In [18]:
df['content'][1]

['Theo ghi nhận của pv báo giao thông trong chiều 31 1 tức mùng 3 tết , lưu lượng phương tiện tại cửa ngõ phía nam thủ đô tăng cao và xuất hiện tình trạng ùn ứ',
 'Thời điểm 15 giờ chiều nay, hàng dài ô tô nối đuôi nhau di chuyển chậm trên cao tốc pháp vân cầu giẽ hướng vào trung tâm tp hà nội',
 'Ùn ứ hàng km khiến nhiều phương tiện đi vào làn dừng khẩn cấp bất chấp quy định cấm',
 'Dù chưa hết kỳ nghỉ tết nguyên đán ất tỵ 2025 nhưng nhiều người đã chủ động trở lại thủ đô sớm',
 'Cảnh đối lập giữa hướng về trung tâm hà nội và hướng đi các tỉnh phía nam trên cao tốc pháp vân cầu giẽ',
 'Lực lượng chức năng đã có mặt từ sớm trên cao tốc pháp vân cầu giẽ để phân làn cho các phương tiện',
 'Hình ảnh chiến sĩ csgt căng mình làm nhiệm vụ, đảm bảo người dân đi lại an toàn, thuận tiện',
 'Đường vành đai 3 lúc cuối giờ chiều, xe cộ cũng tăng vọt theo hướng vào trung tâm hà nội',
 'Dự báo trong những ngày tới, lưu lượng phương tiện tại các cửa ngõ của hà nội sẽ tăng cao do người dân trở lại để bắt đầu làm việc vào ngày mùng 6 tết']

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("VietAI/vit5-base")

df['content'] = df['content'].astype(str)
# Tokenize trực tiếp trên df['content']

df['tokens'] = df['content'].apply(lambda x: tokenizer.tokenize(x))

df['input_ids'] = df['content'].apply(lambda x: tokenizer.encode(x, add_special_tokens=True))

In [22]:
df['tokens'][0]

['▁[',
 "'",
 'Th',
 'ông',
 '▁tin',
 '▁trên',
 '▁tài',
 '▁khoản',
 '▁mạng',
 '▁xã',
 '▁hội',
 '▁x',
 ',',
 '▁bộ',
 '▁trưởng',
 '▁giao',
 '▁thông',
 '▁mỹ',
 '▁se',
 'an',
 '▁du',
 'ffy',
 '▁khẳng',
 '▁định',
 '▁"',
 'h',
 'iện',
 '▁đang',
 '▁trong',
 '▁quá',
 '▁trình',
 '▁xây',
 '▁dựng',
 '▁kế',
 '▁hoạch',
 '▁cải',
 '▁cách',
 '▁f',
 'a',
 'a',
 "'",
 ',',
 "▁'",
 'Tôi',
 '▁hy',
 '▁vọng',
 '▁sẽ',
 '▁sớm',
 '▁công',
 '▁bố',
 '▁kế',
 '▁hoạch',
 '▁này',
 '"',
 "'",
 ',',
 "▁'",
 'Tr',
 'ước',
 '▁đó',
 ',',
 '▁khi',
 '▁hay',
 '▁tin',
 '▁về',
 '▁vụ',
 '▁tai',
 '▁nạn',
 '▁thảm',
 '▁khốc',
 '▁thời',
 '▁điểm',
 '▁máy',
 '▁bay',
 '▁dân',
 '▁dụng',
 '▁của',
 '▁hãng',
 '▁hàng',
 '▁không',
 '▁amer',
 'ican',
 '▁air',
 'lines',
 '▁và',
 '▁máy',
 '▁bay',
 '▁quân',
 '▁sự',
 '▁black',
 '▁h',
 'awk',
 '▁khi',
 '▁đang',
 '▁đến',
 '▁gần',
 '▁sân',
 '▁bay',
 '▁quốc',
 '▁gia',
 '▁r',
 'onald',
 '▁re',
 'agan',
 '▁w',
 'ashi',
 'ngton',
 '▁và',
 '▁rơi',
 '▁xuống',
 '▁sông',
 '▁pot',
 'omac',
 '▁ngày',
 '▁3',
 '0',
 '▁1',
 '▁theo',
 '▁giờ',
 '▁địa',
 '▁phương',
 '▁khiến',
 '▁6',
 '7',
 '▁người',
 '▁thiệt',
 '▁mạng',
 ',',
 '▁tổng',
 '▁thống',
 '▁mỹ',
 '▁d',
 'onald',
 '▁tr',
 'ump',
 '▁chỉ',
 '▁trích',
 '▁gay',
 '▁gắt',
 '▁những',
 '▁nỗ',
 '▁lực',
 '▁đa',
 '▁dạng',
 '▁hóa',
 '▁của',
 '▁f',
 'a',
 'a',
 '▁đồng',
 '▁thời',
 '▁chỉ',
 '▁đạo',
 '▁lập',
 '▁tức',
 '▁có',
 '▁đánh',
 '▁giá',
 '▁về',
 '▁an',
 '▁toàn',
 '▁hàng',
 '▁không',
 "'",
 ',',
 "▁'",
 'B',
 'ộ',
 '▁trưởng',
 '▁giao',
 '▁thông',
 '▁mỹ',
 '▁se',
 'an',
 '▁du',
 'ffy',
 '▁phát',
 '▁biểu',
 '▁trước',
 '▁báo',
 '▁giới',
 '▁theo',
 '▁ông',
 '▁tr',
 'ump',
 ',',
 '▁những',
 '▁nỗ',
 '▁lực',
 '▁thúc',
 '▁đẩy',
 '▁sự',
 '▁đa',
 '▁dạng',
 '▁tại',
 '▁f',
 'a',
 'a',
 '▁có',
 '▁thể',
 '▁là',
 '▁nguyên',
 '▁nhân',
 '▁gây',
 '▁ra',
 '▁vụ',
 '▁tai',
 '▁nạn',
 "'",
 ',',
 "▁'",
 'T',
 'ại',
 '▁cuộc',
 '▁họp',
 '▁báo',
 '▁ở',
 '▁nhà',
 '▁trắng',
 ',',
 '▁ông',
 '▁tr',
 'ump',
 '▁chỉ',
 '▁trích',
 '▁gay',
 '▁gắt',
 '▁bộ',
 '▁trưởng',
 '▁bộ',
 '▁giao',
 '▁thông',
 '▁p',
 'ete',
 '▁bu',
 'tt',
 'ig',
 'ieg',
 '▁dưới',
 '▁thời',
 '▁tổng',
 '▁thống',
 '▁j',
 'oe',
 '▁b',
 'iden',
 '▁là',
 '▁thảm',
 '▁họa',
 ',',
 '▁phá',
 '▁hỏng',
 '▁mọi',
 '▁thứ',
 '▁chỉ',
 '▁vì',
 '▁đa',
 '▁dạng',
 "'",
 ',',
 "▁'",
 'F',
 'a',
 'a',
 '▁đang',
 '▁thiếu',
 '▁khoảng',
 '▁3',
 "'",
 ',',
 "▁'",
 '0',
 '0',
 '0',
 '▁nhân',
 '▁viên',
 '▁kiểm',
 '▁soát',
 '▁không',
 '▁lưu',
 '▁so',
 '▁với',
 '▁mục',
 '▁tiêu',
 '▁đề',
 '▁ra',
 "'",
 ',',
 "▁'",
 'N',
 'ăm',
 '▁2',
 '0',
 '2',
 '3',
 ',',
 '▁cơ',
 '▁quan',
 '▁này',
 '▁cho',
 '▁biết',
 '▁có',
 '▁1',
 '0',
 "'",
 ',',
 "▁'",
 '7',
 '0',
 '0',
 '▁nhân',
 '▁viên',
 '▁kiểm',
 '▁soát',
 '▁không',
 '▁lưu',
 '▁được',
 '▁cấp',
 '▁chứng',
 '▁chỉ',
 ',',
 '▁tương',
 '▁đương',
 '▁năm',
 '▁trước',
 "'",
 ',',
 "▁'",
 'Đ',
 'áp',
 '▁lại',
 ',',
 '▁ông',
 '▁bu',
 'tt',
 'ig',
 'ieg',
 '▁cũng',
 '▁chỉ',
 '▁trích',
 '▁ông',
 '▁tr',
 'ump',
 '▁trên',
 '▁mạng',
 '▁xã',
 '▁hội',
 '▁và',
 '▁cho',
 '▁rằng',
 '▁"',
 'trong',
 '▁lúc',
 '▁gia',
 '▁đình',
 '▁các',
 '▁thân',
 '▁nhân',
 '▁đau',
 '▁buồn',
 ',',
 '▁ông',
 '▁tr',
 'ump',
 '▁nên',
 '▁là',
 '▁người',
 '▁dẫn',
 '▁đầu',
 ',',
 '▁không',
 '▁phải',
 '▁là',
 '▁người',
 '▁nói',
 '▁dối',
 "'",
 ',',
 "▁'",
 'Ch',
 'úng',
 '▁tôi',
 '▁luôn',
 '▁đặt',
 '▁sự',
 '▁an',
 '▁toàn',
 '▁lên',
 '▁hàng',
 '▁đầu',
 ',',
 '▁giảm',
 '▁thiểu',
 '▁các',
 '▁vụ',
 '▁tai',
 '▁nạn',
 '▁thảm',
 '▁khốc',
 ',',
 '▁tăng',
 '▁cường',
 '▁kiểm',
 '▁soát',
 '▁không',
 '▁lưu',
 '▁và',
 '▁không',
 '▁có',
 '▁trường',
 '▁hợp',
 '▁tử',
 '▁vong',
 '▁nào',
 '▁do',
 '▁tai',
 '▁nạn',
 '▁hàng',
 '▁không',
 '▁thương',
 '▁mại',
 '▁trong',
 '▁số',
 '▁hàng',
 '▁triệu',
 '▁chuyến',
 '▁bay',
 '▁mà',
 '▁chúng',
 '▁tôi',
 '▁giám',
 '▁sát',
 '"',
 ',',
 '▁ông',
 '▁bu',
 'tt',
 'ig',
 'ieg',
 '▁cho',
 '▁biết',
 "'",
 ',',
 "▁'",
 'L',
 'ã',
 'nh',
 '▁đạo',
 '▁đảng',
 '▁dân',
 '▁chủ',
 '▁tại',
 '▁thượng',
 '▁viện',
 '▁chu',
 'ck',
 '▁sch',
 'umer',
 '▁cũng',
 '▁chỉ',
 '▁trích',
 '▁bình',
 '▁luận',
 '▁của',
 '▁ông',
 '▁tr',
 'ump',
 '▁gọi',
 '▁đây',
 '▁là',
 '▁suy',
 '▁đoán',
 '▁vô',
 '▁căn',
 '▁cứ',
 "'",
 ',',
 "▁'",
 'Ch',
 'ỉ',
 '▁một',
 '▁ngày',
 '▁sau',
 '▁thảm',
 '▁hoạ',
 ',',
 '▁ông',
 '▁tr',
 'ump',
 '▁cho',
 '▁biết',
 '▁đã',
 '▁bổ',
 '▁nhiệm',
 '▁ông',
 '▁ch',
 'ris',
 '▁r',
 'och',
 'ele',
 'au',
 ',',
 '▁một',
 '▁cựu',
 '▁quan',
 '▁chức',
 '▁hàng',
 '▁không',
 '▁cấp',
 '▁cao',
 '▁làm',
 '▁quyền',
 '▁giám',
 '▁đốc',
 '▁f',
 'a',
 'a',
 "'",
 ',',
 "▁'",
 'Ô',
 'ng',
 '▁ch',
 'ris',
 '▁r',
 'och',
 'ele',
 'au',
 '▁là',
 '▁cựu',
 '▁chiến',
 '▁binh',
 '▁không',
 '▁quân',
 '▁hoa',
 '▁kỳ',
 ',',
 '▁đã',
 '▁làm',
 '▁việc',
 '▁tại',
 '▁f',
 'a',
 'a',
 '▁hơn',
 '▁2',
 '0',
 '▁năm',
 ',',
 '▁trước',
 '▁đây',
 '▁là',
 '▁giám',
 '▁đốc',
 '▁điều',
 '▁hành',
 '▁của',
 '▁hiệp',
 '▁hội',
 '▁hàng',
 '▁không',
 '▁doanh',
 '▁nghiệp',
 '▁quốc',
 '▁gia',
 "'",
 ',',
 "▁'",
 'H',
 'ãng',
 '▁tin',
 '▁re',
 'u',
 'ters',
 '▁dẫn',
 '▁một',
 '▁số',
 '▁nguồn',
 '▁tin',
 '▁cho',
 '▁biết',
 ',',
 '▁ông',
 '▁r',
 'och',
 'ele',
 'au',
 '▁đã',
 '▁làm',
 '▁việc',
 '▁tại',
 '▁f',
 'a',
 'a',
 '▁từ',
 '▁tuần',
 '▁trước',
 "'",
 ',',
 "▁'",
 'Ô',
 'ng',
 '▁m',
 'ike',
 '▁whit',
 'aker',
 '▁vốn',
 '▁được',
 '▁thống',
 '▁nhất',
 '▁là',
 '▁giám',
 '▁đốc',
 '▁f',
 'a',
 'a',
 '▁vào',
 '▁tháng',
 '▁1',
 '0',
 '▁2',
 '0',
 '2',
 '3',
 '▁nhưng',
 '▁đã',
 '▁từ',
 '▁chức',
 '▁sớm',
 '▁sau',
 '▁nhiệm',
 '▁kỳ',
 '▁5',
 '▁năm',
 '▁vào',
 '▁ngày',
 '▁2',
 '0',
 '▁1',
 '▁khi',
 '▁ông',
 '▁tr',
 'ump',
 '▁nhậm',
 '▁chức',
 "'",
 ',',
 "▁'",
 'Ở',
 '▁cương',
 '▁vị',
 '▁mới',
 ',',
 '▁ông',
 '▁r',
 'och',
 'ele',
 'au',
 '▁không',
 '▁chỉ',
 '▁phải',
 '▁giải',
 '▁quyết',
 '▁hậu',
 '▁quả',
 '▁vụ',
 '▁tai',
 '▁nạn',
 '▁ở',
 '▁w',
 'ashi',
 'ngton',
 '▁mà',
 '▁còn',
 '▁phải',
 '▁đối',
 '▁mặt',
 '▁với',
 '▁những',
 '▁vấn',
 '▁đề',
 '▁quan',
 '▁trọng',
 '▁trong',
 '▁vai',
 '▁trò',
 '▁quyền',
 '▁lãnh',
 '▁đạo',
 '▁f',
 'a',
 'a',
 '▁bao',
 '▁gồm',
 '▁quyết',
 '▁định',
 '▁thời',
 '▁điểm',
 '▁cho',
 '▁phép',
 '▁b',
 'oe',
 'ing',
 '▁để',
 '▁thúc',
 '▁đẩy',
 '▁sản',
 '▁xuất',
 '▁7',
 '3',
 '7',
 '▁max',
 '▁sau',
 '▁sự',
 '▁cố',
 '▁khẩn',
 '▁cấp',
 '▁hồi',
 '▁tháng',
 '▁1',
 '▁2',
 '0',
 '2',
 '4',
 "'",
 ']']